export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const FETCH_GOOGLE_USER = "FETCH_GOOGLE_USER";
export const LOGOUT_GOOGLE_USER = "LOGOUT_GOOGLE_USER";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILE = "GET_PROFILE";
